file(GLOB_RECURSE SANDBOX_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
file(GLOB_RECURSE SANDBOX_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/header/*.h")

set(SANDBOX_BIN_NAME "Sandbox-${CMAKE_SYSTEM_NAME}-${ARCHITECTURE}")
add_executable(${SANDBOX_BIN_NAME} "${SANDBOX_SOURCES}" "${SANDBOX_HEADERS}")

target_include_directories(${SANDBOX_BIN_NAME} PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}/header"
)

target_link_libraries(${SANDBOX_BIN_NAME} PRIVATE
    VKRE
)

set_target_properties(${SANDBOX_BIN_NAME} PROPERTIES 
    RUNTIME_OUTPUT_DIRECTORY "${OutputDir}"
    DEBUGGER_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    XCODE_SCHEME_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
)
